# inputs: permite agregar parámetros antes de ejecutar el workflow
# workflow_dispatch: permite ejecutar el workflow manualmente
# gh api: permite hacer llamadas a la API de GitHub
# GH_TOKEN: variable de github, debe tener exactamente el nombre GH_TOKEN
# My_SECRET_TOKEN: PAT (Personal Access Token) de GitHub creado como "Repository secrets"

# Este workflow crea una nueva rama con el nombre del usuario que se le pase como parámetro y
# invita al usuario a colaborar en el repositorio con permisos de push.

name: Create Branch for Interview

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username to grant push permissions"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.inputs.username }} origin/main
          git push origin ${{ github.event.inputs.username }}

      - name: Set push permissions
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/collaborators/${{ github.event.inputs.username }} \
          -f "permission=push"
        env:
          GH_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
