# El token remplaza el login y password de github que se necesita para hacer push: https://${GH_TOKEN}@github.com/${REPO_OWNER}/interview-${USERNAME}.git

name: Create Repository for Interview

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Github username of the candidate"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    env:
      REPOSITORY: ${{ github.repository }}
      REPOSITORY_OWNER: ${{ github.repository_owner }}
      USERNAME: ${{ github.event.inputs.username }}
      GH_TOKEN: ${{ secrets.MY_SECRET_TOKEN_4 }}

    steps:
      - name: Duplicate repository
        run: |
          gh repo create interview-${USERNAME} --private
          git clone --bare https://github.com/${REPOSITORY}.git
          cd $(basename ${REPOSITORY} .git).git
          git push --mirror https://${GH_TOKEN}@github.com/${REPOSITORY_OWNER}/interview-${USERNAME}.git

      - name: Set push permissions for candidate
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${REPOSITORY_OWNER}/interview-${USERNAME}/collaborators/${USERNAME} \
          -f "permission=push"
