name: Create Branch for Interview

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username to grant push permissions"
        required: true

permissions: write-all
  # contents: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.inputs.username }} origin/main
          git push origin ${{ github.event.inputs.username }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set push permissions
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/collaborators/${{ github.event.inputs.username }} \
          -f "permission=push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
