name: Create Branch for Interview

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username of the candidate"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create new interview branch
        run: |
          git checkout -b interview-${{ github.event.inputs.username }} origin/main
          git push origin interview-${{ github.event.inputs.username }}

      - name: Set push permissions for candidate
        run: |
          gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/collaborators/${{ github.event.inputs.username }} \
          -f "permission=push"
        env:
          GH_TOKEN: ${{ secrets.MY_SECRET_TOKEN_2 }}
