name: Create Repository for Interview

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username of the candidate"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4

      # - name: Create new interview branch
      #   run: |
      #     git checkout -b interview-${{ github.event.inputs.username }} origin/main
      #     git push origin interview-${{ github.event.inputs.username }}
      # - name: Create new repository
      #   run: |
      #     gh repo create interview-${{ github.event.inputs.username }} --public --clone
      #     cd interview-${{ github.event.inputs.username }}
      #     git remote add origin https://github.com/${{ github.repository_owner }}/interview-${{ github.event.inputs.username }}.git
      #     git push -u origin main
      #   env:
      #     GH_TOKEN: ${{ secrets.MY_SECRET_TOKEN_2 }}

      # clona el repositorio
      - name: Checkout base repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      # apunta a otro remoto para obtener su rama main
      - name: Create new repository
        run: |
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }} .git)
        env:
          GH_TOKEN: ${{ secrets.SUPER_TOKEN }}

          # gh repo create interview-${{ github.event.inputs.username }} --public --clone
          # cd interview-${{ github.event.inputs.username }}
          # git remote add base https://github.com/${{ github.repository }}.git
          # git fetch base
          # git checkout -b main base/main
          # git remote remove origin
          # git remote add origin https://github.com/${{ github.repository_owner }}/interview-${{ github.event.inputs.username }}.git
          # git push -u origin main


      # - name: Set push permissions for Candidate
      #   run: |
      #     gh api \
      #     --method PUT \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     /repos/${{ github.repository }}/collaborators/${{ github.event.inputs.username }} \
      #     -f "permission=push"
      #   env:
      #     GH_TOKEN: ${{ secrets.MY_SECRET_TOKEN_2 }}
