name: Create Repository for Interview

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username of the candidate"
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest

    # env:
    #   USERNAME: ${{ github.event.inputs.username }}
    #   REPO_OWNER: ${{ github.repository_owner }}
    #   REPO: ${{ github.repository }}
    #   GH_TOKEN: ${{ secrets.SUPER_TOKEN }}

    steps:
      - name: Duplicate repository
        run: |
          gh repo create interview-${USERNAME} --private
          git clone --bare https://github.com/${REPO}.git
          cd $(basename ${REPO} .git).git
          git push --mirror https://${GH_TOKEN}@github.com/${REPO_OWNER}/interview-${USERNAME}.git
        env:
          REPO: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          USERNAME: ${{ github.event.inputs.username }}
          GH_TOKEN: ${{ secrets.SUPER_TOKEN }}

      # - name: Set push permissions for candidate
      #   run: |
      #     gh api \
      #     --method PUT \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     /repos/${{ github.repository }}/collaborators/${{ github.event.inputs.username }} \
      #     -f "permission=push"

      # gh repo create interview-${{ github.event.inputs.username }} --public --clone
      # cd interview-${{ github.event.inputs.username }}
      # git remote add base https://github.com/${{ github.repository }}.git
      # git fetch base
      # git checkout -b main base/main
      # git remote remove origin
      # git remote add origin https://github.com/${{ github.repository_owner }}/interview-${{ github.event.inputs.username }}.git
      # git push -u origin main

      # git remote set-url origin https://github.com/${{ github.repository_owner }}/interview-${{ github.event.inputs.username }}.git
      # git remote -v
